version: '3.8'

services:
  app:
    build: .
    container_name: languageschool-app
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Переменные базы данных
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      
      # Переменные приложения
      FLYWAY_ENABLED: ${FLYWAY_ENABLED:-false}
    networks:
      - language-school-network

  db:
    image: postgres:15
    container_name: languageschool-db
    environment:
      POSTGRES_DB: ${DB_NAME:-languageschool}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - language-school-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_NAME:-languageschool}"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:

networks:
  language-school-network:
    driver: bridge 