-- Создание последовательности для пользователей
CREATE SEQUENCE IF NOT EXISTS user_id_seq START 1;

-- Создание таблицы пользователей
CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY DEFAULT nextval('user_id_seq'),
    user_name VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    sur_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

-- Создание таблицы курсов
CREATE TABLE IF NOT EXISTS cours (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(10,2) NOT NULL
);

-- Создание таблицы заказов
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    order_date DATE NOT NULL,
    total_cost DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Создание таблицы элементов заказа
CREATE TABLE IF NOT EXISTS order_item (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    cours_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    price DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (cours_id) REFERENCES cours(id)
);

-- Создание связующей таблицы для пользователей и заказов
CREATE TABLE IF NOT EXISTS users_orders (
    user_id BIGINT NOT NULL,
    orders_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, orders_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (orders_id) REFERENCES orders(id)
);

-- Вставка тестовых курсов
INSERT INTO cours (name, description, price) VALUES 
('Английский для начинающих', 'Базовый курс английского языка для новичков', 5000.00),
('Немецкий язык A1', 'Начальный уровень немецкого языка', 4500.00),
('Французский разговорный', 'Развитие разговорных навыков французского языка', 5500.00),
('Испанский интенсив', 'Интенсивный курс испанского языка', 6000.00),
('Итальянский для туристов', 'Практический итальянский для путешествий', 4000.00),
('Китайский HSK1', 'Подготовка к экзамену HSK уровень 1', 7000.00)
ON CONFLICT DO NOTHING; 